version: "3.9"
services:

  smtp:
    image: catatnight/postfix:latest
    restart: always
    environment:
      maildomain: mail.coffeebeans.at
      smtp_user: smtp:pass123

  database:
    image: postgres:latest
    restart: always
#    ports:
#      - "127.0.0.1:5433:5432"
    volumes:
      - database:/var/lib/postgresql/data/db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      PGDATA: /var/lib/postgresql/data/db

  keycloak:
    build: ./keycloak
    restart: always
#    ports:
#      - "127.0.0.1:8443:8443"
    volumes:
      - ./keycloak/keystore.jks:/opt/keycloak/conf/server.keystore:ro
      - ./keycloak/themes:/opt/keycloak/themes:ro
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123!
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      PROXY_ADDRESS_FORWARDING: true
      # replace hostnames below with your domain from the certificate in server.keystore
      KC_HOSTNAME: keycloak.coffeebeans.at
      KEYCLOAK_FRONTEND_URL: https://keycloak.coffeebeans.at:8443
    depends_on:
      - database
      - smtp

  proxy:
    image: nginx:latest
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/certs:/etc/ssl/certs/nginx:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/var/www/html:ro
      - ./nginx/includes:/etc/nginx/includes:ro
    depends_on:
      - keycloak

volumes:
  database:
